import React from 'react'
import DrawerAppBar from '../components/DrawerAppBar'
import Footer from '../components/Footer'
import Head from 'next/head'
import styles from "@/styles/Home.module.css";
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>Plus One Co., Ltd.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <DrawerAppBar />
        <img src="hero_image3.jpg" alt="" className={styles.hero_img} />
        <Footer />
      </main>   
    </>
  )
}
