import React from "react";
import DrawerAppBar from "../components/DrawerAppBar";
import Footer from "../components/Footer";
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import classes from "../components/About.module.css";
import { Inter } from "next/font/google";
import OGP from "@/components/OGP";

const inter = Inter({ subsets: ["latin"] });

export default function About() {
  return (
    <>
      <Head>
        <title>Plus One Co., Ltd.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <OGP />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <DrawerAppBar />
        <div className={classes.container}>
          <h3 className={classes.table_title}>代表挨拶</h3>
          <div className={classes.message}>
            現在、建築・内装工事全般を軸に一般リフォーム請負工事や住宅、店舗建築、現場管理やメンテナンス業務など様々な分野で活動を行っております。
            <br />
            培った技術で創意工夫を追求し、安心・安全に基づいた価値を提供できるよう日々精進しております。
            <br />
            ひとと人との出会いから、心の通うコミュニケーションを大切に末永いお付き合いを心がけております。
            <br />
            <br />
            <br />
            <span className={classes.signature}>
              Plus One株式会社　代表取締役 平 博隆
            </span>
          </div>

          <h3 className={classes.table_title}>会社概要</h3>
          <table className={classes.table}>
            <tr>
              <td>会社名</td>
              <td>Plus One株式会社</td>
            </tr>
            <tr>
              <td>住所</td>
              <td>
                〒371-0224
                <br />
                群馬県前橋市河原浜町705-9
              </td>
            </tr>
            <tr>
              <td>TEL</td>
              <td>027-212-8093</td>
            </tr>
            <tr>
              <td>FAX</td>
              <td>027-212-8049</td>
            </tr>
            <tr>
              <td>MOBILE</td>
              <td>070-4128-6043</td>
            </tr>
            <tr>
              <td>MAIL</td>
              <td>t.plus-one@outlook.com</td>
            </tr>
            <tr>
              <td>代表取締役</td>
              <td>平 博隆</td>
            </tr>
            <tr>
              <td>資本金</td>
              <td>3,000,000円</td>
            </tr>
            <tr>
              <td>設立</td>
              <td>2016年7月</td>
            </tr>
            <tr>
              <td>主な事業内容</td>
              <td>
                建築工事業
                <br />
                内装仕上工事業
                <ul>
                  <li>一般リフォーム請負工事</li>
                  <li>住宅・店舗建築全般</li>
                  <li>現場管理</li>
                  <li>メンテナンス業務</li>
                </ul>
              </td>
            </tr>
            <tr>
              <td>免許登録</td>
              <td>
                二級建築士
                <br />
                2級建築施工管理技士
                <br />
                一般建設業 / 群馬県知事 許可 (般-1) 第25281号
              </td>
            </tr>
          </table>
        </div>
        <Footer />
      </main>
    </>
  );
}
